# Generated by Django 5.0.6 on 2026-07-13 01:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado')], default='PENDING', max_length=16)),
                ('current_providers', models.JSONField(blank=True, default=list)),
                ('monthly_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('traffic_pattern', models.CharField(blank=True, choices=[('REAL_TIME_CONTINUOUS', 'Tiempo real — Cargas continuas'), ('REAL_TIME_BURSTY', 'Tiempo real — Tráfico en ráfagas'), ('BATCH_SCHEDULED', 'Lotes — Ejecuciones programadas'), ('BATCH_ONDEMAND', 'Lotes — Bajo demanda')], default='', max_length=32)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='core.lead')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del proceso')),
                ('execution_type', models.CharField(choices=[('REAL_TIME', 'Tiempo real'), ('BATCH', 'Procesamiento por lotes')], default='REAL_TIME', max_length=16)),
                ('input_tokens', models.IntegerField(default=0, verbose_name='Tokens de entrada promedio')),
                ('output_tokens', models.IntegerField(default=0, verbose_name='Tokens de salida promedio')),
                ('peak_concurrency', models.IntegerField(blank=True, help_text='Pico de concurrencia (solo tiempo real).', null=True)),
                ('monthly_executions', models.IntegerField(blank=True, help_text='Ejecuciones mensuales (solo procesamiento por lotes).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='core.questionnaire')),
            ],
            options={
                'verbose_name': 'Proceso del inventario',
                'verbose_name_plural': 'Procesos del inventario',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='questionnaire',
            index=models.Index(fields=['status'], name='core_questi_status_d756bc_idx'),
        ),
        migrations.AddIndex(
            model_name='processinventory',
            index=models.Index(fields=['execution_type'], name='core_proces_executi_1c92ba_idx'),
        ),
    ]
