# Generated by Django 5.0.6 on 2026-09-16 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_questionnairemetricfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='estado_actualizado_en',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de la reunión'),
        ),
        migrations.AddField(
            model_name='lead',
            name='meeting_link',
            field=models.URLField(blank=True, default='', max_length=500, verbose_name='Enlace de la reunión'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estado',
            field=models.CharField(choices=[('descartado', 'Descartado/Spam'), ('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('reunion_confirmada', 'Reunión Confirmada'), ('diagnostico_enviado', 'Diagnóstico enviado'), ('diagnostico_realizado', 'Diagnóstico realizado'), ('pre_implementacion', 'Pre-implementación'), ('pendiente_implementacion', 'Pendiente de Implementación'), ('servicio_realizado', 'Servicio realizado'), ('mantenimiento_programado', 'Mantenimiento programado')], db_index=True, default='nuevo', max_length=32),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LEAD_NUEVO_RECORDATORIO', 'Recordatorio lead nuevo'), ('REUNION_RECORDATORIO', 'Recordatorio de reunión'), ('REUNION_INMINENTE', 'Reunión inminente (90 min)'), ('MANTENIMIENTO_RECORDATORIO', 'Recordatorio de mantenimiento'), ('DIAGNOSTICO_COMPLETADO', 'Diagnóstico completado')], max_length=40)),
                ('dedupe_key', models.CharField(max_length=200, unique=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='core.lead')),
            ],
            options={
                'verbose_name': 'Registro de notificación',
                'verbose_name_plural': 'Registros de notificación',
                'ordering': ['-enviado_en'],
            },
        ),
        migrations.CreateModel(
            name='LeadEstadoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, default='', max_length=32)),
                ('estado_nuevo', models.CharField(choices=[('descartado', 'Descartado/Spam'), ('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('reunion_confirmada', 'Reunión Confirmada'), ('diagnostico_enviado', 'Diagnóstico enviado'), ('diagnostico_realizado', 'Diagnóstico realizado'), ('pre_implementacion', 'Pre-implementación'), ('pendiente_implementacion', 'Pendiente de Implementación'), ('servicio_realizado', 'Servicio realizado'), ('mantenimiento_programado', 'Mantenimiento programado')], max_length=32)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTO', 'Automático'), ('MIGRACION', 'Migración')], default='MANUAL', max_length=16)),
                ('nota', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_history', to='core.lead')),
            ],
            options={
                'verbose_name': 'Historial de estado del lead',
                'verbose_name_plural': 'Historial de estados de leads',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['lead', '-creado_en'], name='core_leades_lead_id_771b72_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField(db_index=True, verbose_name='Fecha y hora programada')),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_windows', to='core.lead')),
            ],
            options={
                'verbose_name': 'Ventana de mantenimiento',
                'verbose_name_plural': 'Ventanas de mantenimiento',
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['completed', 'scheduled_for'], name='core_mainte_complet_43fb08_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenancewindow',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed', False), ('completed_at__isnull', True)), models.Q(('completed', True), ('completed_at__isnull', False)), _connector='OR'), name='mw_completed_at_coherente'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['lead', 'kind'], name='core_notifi_lead_id_93d11b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['-enviado_en'], name='core_notifi_enviado_846b94_idx'),
        ),
    ]
