# Generated by Django 5.0.6 on 2026-09-17 14:47

import datetime

import django.db.models.deletion
from django.db import migrations, models


def sembrar_booking(apps, schema_editor):
    """Crea el singleton BookingConfig y los 7 DiaHorario con el horario
    inicial acordado: Lunes a Viernes 09:00-18:00 hora Colombia, fin de
    semana desactivado (activable desde /interno/agenda/)."""
    BookingConfig = apps.get_model("core", "BookingConfig")
    DiaHorario = apps.get_model("core", "DiaHorario")
    BookingConfig.objects.get_or_create(pk=1, defaults={"dias_apertura": 30})
    for dia in range(7):
        DiaHorario.objects.get_or_create(
            dia=dia,
            defaults={
                "activo": dia < 5,  # L-V
                "hora_inicio": datetime.time(9, 0),
                "hora_fin": datetime.time(18, 0),
            },
        )


def deshacer_siembra(apps, schema_editor):
    BookingConfig = apps.get_model("core", "BookingConfig")
    DiaHorario = apps.get_model("core", "DiaHorario")
    DiaHorario.objects.all().delete()
    BookingConfig.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_migrar_estados_legado"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dias_apertura",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Días que la agenda permanece abierta hacia el futuro.",
                    ),
                ),
                (
                    "duracion_min",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="Duración de la reunión y del intervalo entre slots (min).",
                    ),
                ),
                (
                    "anticipo_min",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Antelación mínima (min) que debe tener un slot reservable.",
                    ),
                ),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración del booking",
                "verbose_name_plural": "Configuración del booking",
            },
        ),
        migrations.CreateModel(
            name="DiaHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                            (6, "Domingo"),
                        ],
                        unique=True,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("hora_inicio", models.TimeField(default=datetime.time(9, 0))),
                ("hora_fin", models.TimeField(default=datetime.time(18, 0))),
            ],
            options={
                "verbose_name": "Día de horario",
                "verbose_name_plural": "Días de horario",
                "ordering": ["dia"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="telefono",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inicio",
                    models.DateTimeField(db_index=True, verbose_name="Inicio (UTC)"),
                ),
                ("fin", models.DateTimeField(verbose_name="Fin (UTC)")),
                ("duracion_min", models.PositiveIntegerField(default=30)),
                (
                    "zona_horaria",
                    models.CharField(default="America/Bogota", max_length=64),
                ),
                (
                    "consentimiento",
                    models.BooleanField(
                        default=False,
                        verbose_name="Consentimiento de contacto otorgado",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("confirmada", "Confirmada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="confirmada",
                        max_length=16,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="core.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agendamiento",
                "verbose_name_plural": "Agendamientos",
                "ordering": ["inicio"],
                "indexes": [
                    models.Index(
                        fields=["estado", "inicio"],
                        name="core_appoin_estado_05ffff_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("estado", "confirmada")),
                fields=("inicio",),
                name="appointment_slot_confirmado_unico",
            ),
        ),
        migrations.RunPython(sembrar_booking, deshacer_siembra),
    ]
