# Generated by Django 5.2.17 on 2026-09-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bookingconfig_diahorario_lead_telefono_appointment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingconfig',
            name='anticipo_min',
            field=models.PositiveIntegerField(default=1440, help_text='Antelación mínima (min) que debe tener un slot reservable (mínimo 24hr = 1440 min).'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='kind',
            field=models.CharField(choices=[('LEAD_NUEVO_RECORDATORIO', 'Recordatorio lead nuevo'), ('REUNION_RECORDATORIO', 'Recordatorio de reunión'), ('REUNION_INMINENTE', 'Reunión inminente (90 min)'), ('MANTENIMIENTO_RECORDATORIO', 'Recordatorio de mantenimiento'), ('DIAGNOSTICO_COMPLETADO', 'Diagnóstico completado'), ('AGENDAMIENTO_CLIENTE', 'Confirmación al cliente (booking)'), ('AGENDAMIENTO_INTERNO', 'Aviso interno (booking)')], max_length=40),
        ),
    ]
